### PR TITLE
Flush rewrite rules only once, group hooks and methods, fix WPCS

### LINKED ISSUE #2: Flushing rewrites on init
Should look at using `register_activation_hook` instead because it only needs to be run once. Happy to write the PR if you'd like.

### PR DESCRIPTION
**Pull request by kasparsd**
Fixes #2.

- Call `flush_rewrite_rules()` only once during plugin activation.
- Fix some of WordPress coding standard suggestions.
- Group hooks together with functions. Namespace functions by prefixing `json_feed_` to all function names.

See the changeset for additional comments.

### CODE REVIEW

File: feed-template.php [hunk 1]
```diff
@@ -1,6 +1,4 @@
 <?php
-header('Content-Type: application/json; charset=' . get_option('blog_charset'));
```
Comment (kasparsd) [inline feed-template.php]: WordPress already adds this here https://github.com/WordPress/WordPress/blob/493f76a3d2ef8c030ab5dcd4333f9a401208f534/wp-includes/class-wp.php#L423

File: feed-template.php [hunk 2]
```diff
@@ -32,4 +30,3 @@
 );
 
 echo json_encode($feed_json, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES);
-?>
```
Comment (kasparsd) [inline feed-template.php]: Removing closing PHP tags [per WPCS](https://make.wordpress.org/core/handbook/best-practices/coding-standards/php/#remove-trailing-spaces).

File: jsonfeed-wp.php [hunk 3]
```diff
@@ -11,41 +11,34 @@
...
-add_action('wp_head', 'json_feed_link');
-
-function setup_feed_rewrite()
-{
-    // Register our function as the feed generator for the /feed/json URL
-    add_feed('json', 'generateJSONFeed');
+// Flush the rewrite rules to enable the json feed permalink
+register_activation_hook( __FILE__, 'json_feed_setup_rewrite' );
+function json_feed_setup_rewrite() {
+	json_feed_setup_feed();
```
Comment (kasparsd) [inline jsonfeed-wp.php]: Be sure to call `add_feed()` which adds the [required rewrite](https://github.com/WordPress/WordPress/blob/dd6da701b286579819cd6aa518aa2d7018efd759/wp-includes/rewrite.php#L248) rule before re-generating the saving the rewrite rules.

File: jsonfeed-wp.php [hunk 4]
```diff
@@ -11,41 +11,34 @@
...
+		'<link rel="alternate" type="application/json" title="JSON Feed" href="%s" />',
+		esc_url( get_feed_link( 'json' ) )
+	);
 }
-
-function json_feed_link()
-{
-   echo '<link rel="alternate" type="application/json" title="JSON Feed" href="' . esc_url( get_feed_link('json') ) . "\" />\n";
-
-   return false;
```
Comment (kasparsd) [inline jsonfeed-wp.php]: No need to `return` on `add_action()`.

**Comment by danielpunkass** [comment]
Thanks for all these contributios, @kasparsd !

**Comment by manton** [comment]
Thanks @kasparsd! Looks good, just finished testing these changes this morning and will start merging things in.
